# config.yaml
verses: "files/en_kjv.json"
prayers: "files/prayers.json"
trivia_level_1: "files/questions1.json"
trivia_level_2: "files/questions2.json"
trivia_level_3: "files/questions3.json"
trivia_channel_id: 1120358578256093385
prayer_channel_id: 1121786563995631666
prayer_list: "files/prayer_list.json"
prayer_text: "files/prayers_list.json"
